-- >>> 20260720010001_drop_demo_schema.sql

-- BW-CRM: wipe demo/training tables from the original setup-supabase*.sql era.
-- Safe: no production users; data was disposable demo only.

-- Auth-era helpers/tables that FKs into old customers (TEXT ids)
drop function if exists public.is_admin() cascade;
drop table if exists public.profiles cascade;

drop table if exists public.tasks cascade;
drop table if exists public.projects cascade;
drop table if exists public.customers cascade;

-- Any partial v1 objects from a failed apply
drop table if exists public.competitor_snapshots cascade;
drop table if exists public.metrics_snapshots cascade;
drop table if exists public.artifacts cascade;
drop table if exists public.assets cascade;
drop table if exists public.project_deliverables cascade;
drop table if exists public.project_stages cascade;

-- Leftover types from earlier experiments / failed applies
drop type if exists public.customer_lifecycle cascade;
drop type if exists public.deliverable_type cascade;
drop type if exists public.deliverable_status cascade;
drop type if exists public.task_status cascade;
drop type if exists public.task_type cascade;
drop type if exists public.asset_type cascade;
drop type if exists public.artifact_type cascade;
drop type if exists public.artifact_status cascade;
drop type if exists public.content_type cascade;
drop type if exists public.snapshot_type cascade;
drop type if exists public.competitor_type cascade;
drop type if exists public.connection_status cascade;



-- >>> 20260720010002_core_schema.sql

-- BW-CRM schema v1 â€” enums, tables, indexes, seed
-- Ground truth: docs/schema-v1.md

create schema if not exists private;

-- â”€â”€ Enums â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create type public.customer_lifecycle as enum ('lead', 'customer', 'inactive');
create type public.deliverable_type as enum (
  'goal_target',
  'collection_of_work',
  'guaranteed_outcome'
);
create type public.deliverable_status as enum (
  'planned',
  'in_progress',
  'done',
  'dropped'
);
create type public.task_status as enum (
  'not_started',
  'in_progress',
  'blocked',
  'completed'
);
create type public.task_type as enum ('task', 'agent_task', 'internal');
create type public.asset_type as enum ('website', 'staging', 'other');
create type public.artifact_type as enum ('report', 'data', 'proposal', 'other');
create type public.artifact_status as enum ('draft', 'final', 'archived');
create type public.content_type as enum ('link', 'md', 'json', 'csv', 'other');
create type public.snapshot_type as enum ('baseline', 'update');
create type public.competitor_type as enum ('competitor', 'target', 'business');
create type public.connection_status as enum (
  'unknown',
  'connected',
  'error',
  'disconnected'
);

-- â”€â”€ project_stages â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.project_stages (
  stage      smallint not null,
  step       smallint not null,
  stage_name text     not null,
  step_name  text     not null,
  ordinal    smallint not null unique,
  primary key (stage, step)
);

insert into public.project_stages (stage, step, stage_name, step_name, ordinal) values
  (1, 0, 'Proposal',         'Active', 0),
  (2, 0, 'Onboard & Design', 'Active', 1),
  (3, 0, 'Build',            'Active', 2),
  (4, 0, 'Review',           'Active', 3),
  (5, 0, 'Refine',           'Active', 4),
  (6, 0, 'Live',             'Active', 5),
  (7, 0, 'Closed',           'Active', 6);

-- â”€â”€ customers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.customers (
  id                  bigint generated by default as identity primary key,
  business_name       text not null,
  contact_first_name  text not null default '',
  contact_last_name   text not null default '',
  email               text not null default '',
  phone               text not null default '',
  address             text not null default '',
  location            text not null default '',
  website             text not null default '',
  contact_method      text not null default 'Email',
  lifecycle           public.customer_lifecycle not null default 'lead',
  notes               text not null default '',
  version             integer not null default 1,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index customers_lifecycle_idx on public.customers (lifecycle);
create index customers_business_name_idx on public.customers (lower(business_name));

-- â”€â”€ projects â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
-- proposal_artifact_id FK added after artifacts exists (soft create-time cycle).
create table public.projects (
  id                    bigint generated by default as identity primary key,
  customer_id           bigint not null references public.customers (id) on delete restrict,
  name                  text not null,
  system_description    text not null default '',
  stage                 smallint not null default 1,
  step                  smallint not null default 0,
  notes                 text not null default '',
  proposal              text not null default '',
  proposal_artifact_id  bigint null,
  start_on              date null,
  deadline              date null,
  completed_on          date null,
  version               integer not null default 1,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  foreign key (stage, step) references public.project_stages (stage, step)
);

create index projects_customer_id_idx on public.projects (customer_id);
create index projects_stage_step_idx on public.projects (stage, step);

-- â”€â”€ assets â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.assets (
  id                     bigint generated by default as identity primary key,
  customer_id            bigint not null references public.customers (id) on delete restrict,
  project_id             bigint null references public.projects (id) on delete set null,
  asset_type             public.asset_type not null default 'website',
  name                   text not null default '',
  asset_url              text not null default '',
  health_score           numeric null,
  conversion_event_name  text not null default '',
  gsc_status             public.connection_status not null default 'unknown',
  ga4_status             public.connection_status not null default 'unknown',
  wp_cli_status          public.connection_status not null default 'unknown',
  hermes_profile         text not null default '',
  telegram_topic         text not null default '',
  workspace              text not null default '',
  version                integer not null default 1,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create index assets_customer_id_idx on public.assets (customer_id);
create index assets_project_id_idx on public.assets (project_id);

-- â”€â”€ artifacts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.artifacts (
  id             bigint generated by default as identity primary key,
  customer_id    bigint not null references public.customers (id) on delete restrict,
  asset_id       bigint null references public.assets (id) on delete set null,
  project_id     bigint null references public.projects (id) on delete set null,
  title          text not null,
  artifact_type  public.artifact_type not null default 'other',
  status         public.artifact_status not null default 'draft',
  summary        text not null default '',
  content_type   public.content_type not null default 'link',
  path_or_url    text not null default '',
  bytes          bigint null,
  version        integer not null default 1,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index artifacts_customer_id_idx on public.artifacts (customer_id);
create index artifacts_asset_id_idx on public.artifacts (asset_id);
create index artifacts_project_id_idx on public.artifacts (project_id);

alter table public.projects
  add constraint projects_proposal_artifact_id_fkey
  foreign key (proposal_artifact_id) references public.artifacts (id) on delete set null;

create index projects_proposal_artifact_id_idx on public.projects (proposal_artifact_id);

-- â”€â”€ project_deliverables â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.project_deliverables (
  id          bigint generated by default as identity primary key,
  project_id  bigint not null references public.projects (id) on delete cascade,
  title       text not null,
  type        public.deliverable_type not null,
  status      public.deliverable_status not null default 'planned',
  stage       smallint null,
  step        smallint null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  foreign key (stage, step) references public.project_stages (stage, step)
);

create index project_deliverables_project_id_idx on public.project_deliverables (project_id);

-- â”€â”€ tasks â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.tasks (
  id           bigint generated by default as identity primary key,
  project_id   bigint null references public.projects (id) on delete set null,
  asset_id     bigint null references public.assets (id) on delete set null,
  customer_id  bigint null references public.customers (id) on delete set null,
  title        text not null,
  notes        text not null default '',
  status       public.task_status not null default 'not_started',
  task_type    public.task_type not null default 'task',
  due_on       date null,
  assigned_to  text not null default '',
  version      integer not null default 1,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index tasks_project_id_idx on public.tasks (project_id);
create index tasks_asset_id_idx on public.tasks (asset_id);
create index tasks_customer_id_idx on public.tasks (customer_id);
create index tasks_status_idx on public.tasks (status);

-- â”€â”€ metrics_snapshots â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.metrics_snapshots (
  id                          bigint generated by default as identity primary key,
  asset_id                    bigint not null references public.assets (id) on delete cascade,
  period_label                text not null,
  snapshot_type               public.snapshot_type not null default 'update',
  domain_rank                 numeric null,
  domain_rank_delta           numeric null,
  clicks                      numeric null,
  clicks_delta                numeric null,
  impressions                 numeric null,
  impressions_delta           numeric null,
  ctr                         numeric null,
  ctr_delta                   numeric null,
  avg_rank                    numeric null,
  avg_rank_delta              numeric null,
  conversions                 numeric null,
  conversions_delta           numeric null,
  engagement_rate             numeric null,
  engagement_rate_delta       numeric null,
  avg_session_duration        numeric null,
  avg_session_duration_delta  numeric null,
  version                     integer not null default 1,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

create index metrics_snapshots_asset_id_idx on public.metrics_snapshots (asset_id);
create index metrics_snapshots_period_label_idx on public.metrics_snapshots (period_label);

-- â”€â”€ competitor_snapshots â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create table public.competitor_snapshots (
  id                 bigint generated by default as identity primary key,
  asset_id           bigint not null references public.assets (id) on delete cascade,
  type               public.competitor_type not null,
  business_name      text not null,
  url                text not null default '',
  location           text not null default '',
  notes              text not null default '',
  total_keywords     numeric null,
  organic_traffic    numeric null,
  traffic_value      numeric null,
  paid_traffic       numeric null,
  top_3_keywords     numeric null,
  top_10_keywords    numeric null,
  position_1         numeric null,
  position_2_3       numeric null,
  position_4_10      numeric null,
  position_11_20     numeric null,
  keyword_gaps       numeric null,
  backlinks          numeric null,
  referring_domains  numeric null,
  domain_rank        numeric null,
  spam_score         numeric null,
  version            integer not null default 1,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index competitor_snapshots_asset_id_idx on public.competitor_snapshots (asset_id);
create index competitor_snapshots_type_idx on public.competitor_snapshots (type);



-- >>> 20260720010003_rls.sql

-- BW-CRM schema v1 â€” RLS + grants
-- Solo admin for now: authenticated full access; anon blocked.
-- Tighten per-row ownership when profiles / multi-user land.

-- â”€â”€ Enable RLS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
alter table public.project_stages       enable row level security;
alter table public.customers            enable row level security;
alter table public.projects             enable row level security;
alter table public.project_deliverables enable row level security;
alter table public.assets               enable row level security;
alter table public.artifacts            enable row level security;
alter table public.tasks                enable row level security;
alter table public.metrics_snapshots    enable row level security;
alter table public.competitor_snapshots enable row level security;

-- â”€â”€ Grants â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public
  grant usage, select on sequences to authenticated;

-- project_stages is reference data â€” read for all authenticated
create policy "project_stages_select_authenticated"
  on public.project_stages
  for select
  to authenticated
  using (true);

-- Mutating reference data: authenticated for now (solo); lock down later
create policy "project_stages_write_authenticated"
  on public.project_stages
  for all
  to authenticated
  using (true)
  with check (true);

-- â”€â”€ CRUD policies (authenticated, all rows) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
create policy "customers_all_authenticated"
  on public.customers for all to authenticated
  using (true) with check (true);

create policy "projects_all_authenticated"
  on public.projects for all to authenticated
  using (true) with check (true);

create policy "project_deliverables_all_authenticated"
  on public.project_deliverables for all to authenticated
  using (true) with check (true);

create policy "assets_all_authenticated"
  on public.assets for all to authenticated
  using (true) with check (true);

create policy "artifacts_all_authenticated"
  on public.artifacts for all to authenticated
  using (true) with check (true);

create policy "tasks_all_authenticated"
  on public.tasks for all to authenticated
  using (true) with check (true);

create policy "metrics_snapshots_all_authenticated"
  on public.metrics_snapshots for all to authenticated
  using (true) with check (true);

create policy "competitor_snapshots_all_authenticated"
  on public.competitor_snapshots for all to authenticated
  using (true) with check (true);



-- >>> 20260720010004_functions_triggers.sql

-- BW-CRM schema v1 â€” version bump + updated_at triggers

create or replace function private.bump_row_version()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- Tables with version column
create trigger bump_customers_version
  before update on public.customers
  for each row execute function private.bump_row_version();

create trigger bump_projects_version
  before update on public.projects
  for each row execute function private.bump_row_version();

create trigger bump_assets_version
  before update on public.assets
  for each row execute function private.bump_row_version();

create trigger bump_artifacts_version
  before update on public.artifacts
  for each row execute function private.bump_row_version();

create trigger bump_tasks_version
  before update on public.tasks
  for each row execute function private.bump_row_version();

create trigger bump_metrics_snapshots_version
  before update on public.metrics_snapshots
  for each row execute function private.bump_row_version();

create trigger bump_competitor_snapshots_version
  before update on public.competitor_snapshots
  for each row execute function private.bump_row_version();

-- Deliverables: no version column â€” touch updated_at only
create trigger touch_project_deliverables_updated_at
  before update on public.project_deliverables
  for each row execute function private.touch_updated_at();



