-- Phase B2: GSC page metrics + SEO opportunities

create type public.seo_opportunity_priority as enum ('high', 'medium', 'low');
create type public.seo_opportunity_status as enum (
  'open', 'task_created', 'complete', 'dismissed', 'snoozed'
);
create type public.seo_opportunity_type as enum (
  'low_ctr', 'striking_distance', 'page_speed', 'content_refresh',
  'serp_gap', 'indexation', 'thin_content', 'internal_link', 'other'
);

create table public.page_metrics_current (
  id                   bigint generated by default as identity primary key,
  asset_page_id        bigint not null references public.asset_pages (id) on delete cascade,
  period_start         date not null,
  period_end           date not null,
  prior_period_start   date null,
  prior_period_end     date null,
  impressions          numeric not null default 0,
  impressions_delta    numeric not null default 0,
  clicks               numeric not null default 0,
  clicks_delta         numeric not null default 0,
  ctr                  numeric not null default 0,
  ctr_delta            numeric not null default 0,
  avg_position         numeric not null default 0,
  avg_position_delta   numeric not null default 0,
  pulled_at            timestamptz not null default now(),
  version              integer not null default 1,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (asset_page_id)
);

create index page_metrics_current_asset_page_id_idx on public.page_metrics_current (asset_page_id);

alter table public.page_metrics_current enable row level security;
grant select, insert, update, delete on public.page_metrics_current to authenticated;
create policy "page_metrics_current_all_authenticated"
  on public.page_metrics_current for all to authenticated
  using (true) with check (true);

create trigger bump_page_metrics_current_version
  before update on public.page_metrics_current
  for each row execute function private.bump_row_version();

create table public.seo_opportunities (
  id                   bigint generated by default as identity primary key,
  asset_id             bigint not null references public.assets (id) on delete cascade,
  asset_page_id        bigint not null references public.asset_pages (id) on delete cascade,
  opportunity_type     public.seo_opportunity_type not null,
  problem              text not null,
  priority             public.seo_opportunity_priority not null,
  recommended_workflow text not null default '',
  status               public.seo_opportunity_status not null default 'open',
  impressions          numeric not null default 0,
  clicks               numeric not null default 0,
  ctr                  numeric not null default 0,
  avg_position         numeric not null default 0,
  impact_score         numeric null,
  evidence_json        jsonb not null default '{}',
  task_id              bigint null references public.tasks (id) on delete set null,
  detected_at          timestamptz not null default now(),
  resolved_at          timestamptz null,
  version              integer not null default 1,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create unique index seo_opportunities_open_dedup_idx
  on public.seo_opportunities (asset_page_id, opportunity_type)
  where status = 'open';

create index seo_opportunities_asset_status_priority_idx
  on public.seo_opportunities (asset_id, status, priority);
create index seo_opportunities_page_idx on public.seo_opportunities (asset_page_id);

alter table public.seo_opportunities enable row level security;
grant select, insert, update, delete on public.seo_opportunities to authenticated;
create policy "seo_opportunities_all_authenticated"
  on public.seo_opportunities for all to authenticated
  using (true) with check (true);

create trigger bump_seo_opportunities_version
  before update on public.seo_opportunities
  for each row execute function private.bump_row_version();

alter table public.tasks
  add column seo_opportunity_id bigint null references public.seo_opportunities (id) on delete set null,
  add column page_url text not null default '';

create index tasks_seo_opportunity_id_idx on public.tasks (seo_opportunity_id);
