-- Phase A SEO: per-asset integration connections + service-role-only secrets

create table public.asset_connections (
  id            bigint generated by default as identity primary key,
  asset_id      bigint not null references public.assets (id) on delete cascade,
  provider      text not null check (provider in ('gsc', 'ga4', 'wordpress', 'hermes', 'dataforseo', 'ssh')),
  status        public.connection_status not null default 'unknown',
  config        jsonb not null default '{}',
  secret_ref    text not null default '',
  last_sync_at  timestamptz null,
  last_error    text not null default '',
  version       integer not null default 1,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (asset_id, provider)
);

create index asset_connections_asset_id_idx on public.asset_connections (asset_id);

-- Refresh tokens: no RLS policies — edge functions use service role only
create table public.asset_connection_secrets (
  asset_connection_id bigint primary key references public.asset_connections (id) on delete cascade,
  refresh_token       text not null,
  updated_at          timestamptz not null default now()
);

alter table public.asset_connections enable row level security;
alter table public.asset_connection_secrets enable row level security;

grant select, insert, update, delete on public.asset_connections to authenticated;
revoke all on public.asset_connection_secrets from authenticated;
revoke all on public.asset_connection_secrets from anon;

create policy "asset_connections_all_authenticated"
  on public.asset_connections for all to authenticated
  using (true) with check (true);

create trigger bump_asset_connections_version
  before update on public.asset_connections
  for each row execute function private.bump_row_version();
