-- Step 2: migrate live sites + competitor analysis runs

update public.assets
set asset_type = 'managed_website'
where asset_type = 'website';

create type public.competitor_run_status as enum (
  'pending',
  'running',
  'done',
  'failed'
);

create table public.competitor_analysis_runs (
  id                    bigint generated by default as identity primary key,
  asset_id              bigint not null references public.assets (id) on delete cascade,
  search_location_code  integer not null default 2036,
  search_location_name  text not null default 'Australia',
  search_language_code  text not null default 'en',
  competitor_inputs     jsonb not null default '[]'::jsonb,
  status                public.competitor_run_status not null default 'pending',
  error_message         text not null default '',
  version               integer not null default 1,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index competitor_analysis_runs_asset_id_idx
  on public.competitor_analysis_runs (asset_id);
create index competitor_analysis_runs_created_at_idx
  on public.competitor_analysis_runs (asset_id, created_at desc);

alter table public.competitor_snapshots
  add column if not exists run_id bigint null
    references public.competitor_analysis_runs (id) on delete cascade;

alter table public.competitor_snapshots
  add column if not exists top_100_keywords numeric null;

alter table public.competitor_snapshots
  add column if not exists position_21_50 numeric null;

alter table public.competitor_snapshots
  add column if not exists position_51_100 numeric null;

create index if not exists competitor_snapshots_run_id_idx
  on public.competitor_snapshots (run_id);

alter table public.competitor_analysis_runs enable row level security;

create policy "competitor_analysis_runs_all_authenticated"
  on public.competitor_analysis_runs for all to authenticated
  using (true) with check (true);

create trigger bump_competitor_analysis_runs_version
  before update on public.competitor_analysis_runs
  for each row execute function private.bump_row_version();

create trigger touch_competitor_analysis_runs_updated_at
  before update on public.competitor_analysis_runs
  for each row execute function private.touch_updated_at();
