-- BW-CRM schema v1 — enums, tables, indexes, seed
-- Ground truth: docs/schema-v1.md

create schema if not exists private;

-- ── Enums ──────────────────────────────────────────────────────────────
create type public.customer_lifecycle as enum ('lead', 'customer', 'inactive');
create type public.deliverable_type as enum (
  'goal_target',
  'collection_of_work',
  'guaranteed_outcome'
);
create type public.deliverable_status as enum (
  'planned',
  'in_progress',
  'done',
  'dropped'
);
create type public.task_status as enum (
  'not_started',
  'in_progress',
  'blocked',
  'completed'
);
create type public.task_type as enum ('task', 'agent_task', 'internal');
create type public.asset_type as enum ('website', 'staging', 'other');
create type public.artifact_type as enum ('report', 'data', 'proposal', 'other');
create type public.artifact_status as enum ('draft', 'final', 'archived');
create type public.content_type as enum ('link', 'md', 'json', 'csv', 'other');
create type public.snapshot_type as enum ('baseline', 'update');
create type public.competitor_type as enum ('competitor', 'target', 'business');
create type public.connection_status as enum (
  'unknown',
  'connected',
  'error',
  'disconnected'
);

-- ── project_stages ─────────────────────────────────────────────────────
create table public.project_stages (
  stage      smallint not null,
  step       smallint not null,
  stage_name text     not null,
  step_name  text     not null,
  ordinal    smallint not null unique,
  primary key (stage, step)
);

insert into public.project_stages (stage, step, stage_name, step_name, ordinal) values
  (1, 0, 'Proposal',         'Active', 0),
  (2, 0, 'Onboard & Design', 'Active', 1),
  (3, 0, 'Build',            'Active', 2),
  (4, 0, 'Review',           'Active', 3),
  (5, 0, 'Refine',           'Active', 4),
  (6, 0, 'Live',             'Active', 5),
  (7, 0, 'Closed',           'Active', 6);

-- ── customers ──────────────────────────────────────────────────────────
create table public.customers (
  id                  bigint generated by default as identity primary key,
  business_name       text not null,
  contact_first_name  text not null default '',
  contact_last_name   text not null default '',
  email               text not null default '',
  phone               text not null default '',
  address             text not null default '',
  location            text not null default '',
  website             text not null default '',
  contact_method      text not null default 'Email',
  lifecycle           public.customer_lifecycle not null default 'lead',
  notes               text not null default '',
  version             integer not null default 1,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index customers_lifecycle_idx on public.customers (lifecycle);
create index customers_business_name_idx on public.customers (lower(business_name));

-- ── projects ───────────────────────────────────────────────────────────
-- proposal_artifact_id FK added after artifacts exists (soft create-time cycle).
create table public.projects (
  id                    bigint generated by default as identity primary key,
  customer_id           bigint not null references public.customers (id) on delete restrict,
  name                  text not null,
  system_description    text not null default '',
  stage                 smallint not null default 1,
  step                  smallint not null default 0,
  notes                 text not null default '',
  proposal              text not null default '',
  proposal_artifact_id  bigint null,
  start_on              date null,
  deadline              date null,
  completed_on          date null,
  version               integer not null default 1,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  foreign key (stage, step) references public.project_stages (stage, step)
);

create index projects_customer_id_idx on public.projects (customer_id);
create index projects_stage_step_idx on public.projects (stage, step);

-- ── assets ─────────────────────────────────────────────────────────────
create table public.assets (
  id                     bigint generated by default as identity primary key,
  customer_id            bigint not null references public.customers (id) on delete restrict,
  project_id             bigint null references public.projects (id) on delete set null,
  asset_type             public.asset_type not null default 'website',
  name                   text not null default '',
  asset_url              text not null default '',
  health_score           numeric null,
  conversion_event_name  text not null default '',
  gsc_status             public.connection_status not null default 'unknown',
  ga4_status             public.connection_status not null default 'unknown',
  wp_cli_status          public.connection_status not null default 'unknown',
  hermes_profile         text not null default '',
  telegram_topic         text not null default '',
  workspace              text not null default '',
  version                integer not null default 1,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create index assets_customer_id_idx on public.assets (customer_id);
create index assets_project_id_idx on public.assets (project_id);

-- ── artifacts ──────────────────────────────────────────────────────────
create table public.artifacts (
  id             bigint generated by default as identity primary key,
  customer_id    bigint not null references public.customers (id) on delete restrict,
  asset_id       bigint null references public.assets (id) on delete set null,
  project_id     bigint null references public.projects (id) on delete set null,
  title          text not null,
  artifact_type  public.artifact_type not null default 'other',
  status         public.artifact_status not null default 'draft',
  summary        text not null default '',
  content_type   public.content_type not null default 'link',
  path_or_url    text not null default '',
  bytes          bigint null,
  version        integer not null default 1,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index artifacts_customer_id_idx on public.artifacts (customer_id);
create index artifacts_asset_id_idx on public.artifacts (asset_id);
create index artifacts_project_id_idx on public.artifacts (project_id);

alter table public.projects
  add constraint projects_proposal_artifact_id_fkey
  foreign key (proposal_artifact_id) references public.artifacts (id) on delete set null;

create index projects_proposal_artifact_id_idx on public.projects (proposal_artifact_id);

-- ── project_deliverables ───────────────────────────────────────────────
create table public.project_deliverables (
  id          bigint generated by default as identity primary key,
  project_id  bigint not null references public.projects (id) on delete cascade,
  title       text not null,
  type        public.deliverable_type not null,
  status      public.deliverable_status not null default 'planned',
  stage       smallint null,
  step        smallint null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  foreign key (stage, step) references public.project_stages (stage, step)
);

create index project_deliverables_project_id_idx on public.project_deliverables (project_id);

-- ── tasks ──────────────────────────────────────────────────────────────
create table public.tasks (
  id           bigint generated by default as identity primary key,
  project_id   bigint null references public.projects (id) on delete set null,
  asset_id     bigint null references public.assets (id) on delete set null,
  customer_id  bigint null references public.customers (id) on delete set null,
  title        text not null,
  notes        text not null default '',
  status       public.task_status not null default 'not_started',
  task_type    public.task_type not null default 'task',
  due_on       date null,
  assigned_to  text not null default '',
  version      integer not null default 1,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index tasks_project_id_idx on public.tasks (project_id);
create index tasks_asset_id_idx on public.tasks (asset_id);
create index tasks_customer_id_idx on public.tasks (customer_id);
create index tasks_status_idx on public.tasks (status);

-- ── metrics_snapshots ──────────────────────────────────────────────────
create table public.metrics_snapshots (
  id                          bigint generated by default as identity primary key,
  asset_id                    bigint not null references public.assets (id) on delete cascade,
  period_label                text not null,
  snapshot_type               public.snapshot_type not null default 'update',
  domain_rank                 numeric null,
  domain_rank_delta           numeric null,
  clicks                      numeric null,
  clicks_delta                numeric null,
  impressions                 numeric null,
  impressions_delta           numeric null,
  ctr                         numeric null,
  ctr_delta                   numeric null,
  avg_rank                    numeric null,
  avg_rank_delta              numeric null,
  conversions                 numeric null,
  conversions_delta           numeric null,
  engagement_rate             numeric null,
  engagement_rate_delta       numeric null,
  avg_session_duration        numeric null,
  avg_session_duration_delta  numeric null,
  version                     integer not null default 1,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

create index metrics_snapshots_asset_id_idx on public.metrics_snapshots (asset_id);
create index metrics_snapshots_period_label_idx on public.metrics_snapshots (period_label);

-- ── competitor_snapshots ───────────────────────────────────────────────
create table public.competitor_snapshots (
  id                 bigint generated by default as identity primary key,
  asset_id           bigint not null references public.assets (id) on delete cascade,
  type               public.competitor_type not null,
  business_name      text not null,
  url                text not null default '',
  location           text not null default '',
  notes              text not null default '',
  total_keywords     numeric null,
  organic_traffic    numeric null,
  traffic_value      numeric null,
  paid_traffic       numeric null,
  top_3_keywords     numeric null,
  top_10_keywords    numeric null,
  position_1         numeric null,
  position_2_3       numeric null,
  position_4_10      numeric null,
  position_11_20     numeric null,
  keyword_gaps       numeric null,
  backlinks          numeric null,
  referring_domains  numeric null,
  domain_rank        numeric null,
  spam_score         numeric null,
  version            integer not null default 1,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index competitor_snapshots_asset_id_idx on public.competitor_snapshots (asset_id);
create index competitor_snapshots_type_idx on public.competitor_snapshots (type);
