-- Phase B1: managed pages registry (WordPress-owned) + WP REST credentials

create table public.asset_pages (
  id                bigint generated by default as identity primary key,
  asset_id          bigint not null references public.assets (id) on delete cascade,
  url_path          text not null,
  canonical_url     text not null default '',
  wp_post_id        bigint null,
  wp_post_type      text not null default '',
  title             text not null default '',
  is_priority       boolean not null default false,
  scos_next_step    text not null default '',
  scos_index_status text not null default '',
  topic_slug        text not null default '',
  cluster_slug      text not null default '',
  wp_meta_snapshot  jsonb not null default '{}',
  meta_synced_at    timestamptz null,
  version           integer not null default 1,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (asset_id, url_path)
);

create index asset_pages_asset_id_idx on public.asset_pages (asset_id);
create index asset_pages_asset_priority_idx on public.asset_pages (asset_id, is_priority);

alter table public.asset_pages enable row level security;

grant select, insert, update, delete on public.asset_pages to authenticated;

create policy "asset_pages_all_authenticated"
  on public.asset_pages for all to authenticated
  using (true) with check (true);

create trigger bump_asset_pages_version
  before update on public.asset_pages
  for each row execute function private.bump_row_version();

-- WP REST uses application passwords (not OAuth refresh tokens)
alter table public.asset_connection_secrets
  alter column refresh_token drop not null;

alter table public.asset_connection_secrets
  add column wp_username text null,
  add column wp_app_password text null;
